### PR TITLE
Update npm audit to scan workspaces

### PR DESCRIPTION
**Pull request by nmanoogian**
This PR adds the `--workspaces --include-workspace-root` flags to the npm audit command, which scans internal npm workspaces for `npm audit` issues.

### CODE REVIEW

**Review by Piccirello — APPROVED** [review]

**Comment by Kunamatata** [comment]
@nmanoogian I think the `npm audit` command given that the root `package.json` leverages workspaces uses these defaults. I remember having a conversation on this pull request about it:
https://github.com/DopplerHQ/universal-import/pull/23#discussion_r1018461039

What do you think?

**Comment by nmanoogian** [comment]
> @nmanoogian I think the `npm audit` command given that the root `package.json` leverages workspaces uses these defaults. I remember having a conversation on this pull request about it: [#23 (comment)](https://github.com/DopplerHQ/universal-import/pull/23#discussion_r1018461039)
> 
> What do you think?

Ah, that's helpful context. I don't think that `npm audit` automatically reaches into workspaces. From the `npm help audit` docs:

```
   workspaces

       • Default: null

       • Type: null or Boolean


       Set to true to run the command in the context of all configured workspaces.

       Explicitly setting this to false will cause commands like install to ignore workspaces altogether. When not set explicitly:

       • Commands that operate on the node_modules tree (install, update, etc.) will link workspaces into the node_modules folder. - Commands that do other things (test, exec, publish, etc.) will operate on the root project, unless one or more workspaces are specified in the workspace config.


       This value is not exported to the environment for child processes.

   include-workspace-root

       • Default: false

       • Type: Boolean


       Include the workspace root when workspaces are enabled for a command.

       When false, specifying individual workspaces via the workspace config, or all workspaces via the workspaces flag, will cause npm to operate only on the specified workspaces, and not on the root project.

       This value is not exported to the environment for child processes.
```

`npm audit` can operate on the `node_modules` tree when you use the `fix` subcommand but in my testing, `npm audit` did not find advisories in workspaces

**Comment by nmanoogian** [comment]
Hmmm, I just tried locally installing a package with a known advisory in the `core` workspace (with `npm i -w core json5@1.0.1`). I'm getting the same results from `npm audit` and `npm audit --workspaces --include-workspace-root`. I could have sworn that `npm audit` wasn't catching workplace advisories; maybe it changed in a newer version of the command?

With this in mind, I'm OK to close this PR unless anyone has objections.

**Comment by nmanoogian** [comment]
Awesome, thanks for looking into that!

**Pull request closed without merging**
